"""Create Favorite table

Revision ID: 41349305c34b
Revises: 7fc1bf159cd5
Create Date: 2024-12-17 11:59:16.735040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41349305c34b'
down_revision = '7fc1bf159cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    # ### end Alembic commands ###
