"""empty message

Revision ID: 8a9fce1bbf88
Revises: 41349305c34b
Create Date: 2024-12-17 12:36:07.067385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a9fce1bbf88'
down_revision = '41349305c34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
        'fk_favorite_user_id',  # Explicit name for the constraint
        'user',                 # Reference table
        ['user_id'],            # Local column
        ['id']                  # Referenced column
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
